name: 'Daily Weather Notification'

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行（北京时间早上8点）
  workflow_dispatch:

jobs:
  send_weather:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Get Weather'
        run: bash ./weather.sh

      - name: 'Send Weather Report'
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Authorization: Bearer q0a/DTzYO1y0+qNklYXK1IVzrQWer8tbBR7j9x0BsZ0KuVEpdqxIXWPVu15ojoBlJ0LlF3jg58fWA78YMlZDb7DRLO9mDRt4F6zJuXs+xjqJX03JN2UcuhmNRF8vRpQUMGKIr251bZQSn2QpNxpoEwdB04t89/1O/w1cDnyilFU=" \
          -H "Content-Type: application/json" \
          -d '{
                "to": "lafa901120line",
                "messages":[
                  {
                    "type":"text",
                    "text":"今日天氣：$(cat result.txt)"
                  }
                ]
              }'
